using System;
using System.IO;

namespace Backend
{
	public static class CoreFunctions
	{
		/// <summary>
		/// Reads the index.html file generated by Angular CLI and outputs the content into a string.
		/// Note: index.html template should be EMPTY! so only the scripts are output into it.
		/// </summary>
		public static string GetScriptsFromIndexHtml(string rootPath)
		{
			return File.ReadAllText(Path.Combine(rootPath, "wwwroot", "appdist", "index.html"));
		}

		/// <summary>
		/// Parses the current app version to a string
		/// </summary>
		public static string ParseVersion(Version version)
		{
			return $"{version.Major}.{version.Minor}.{version.Build}";
		}
	}
}
