name: BuildOn_Tag

on:
  push:
    tags:
       - '*'

jobs:
# #########################################
# Build Server
# #########################################
  build_server:
    env:
      PATH_BASE: ${{github.workspace}}
      PATH_BASE_APP: ${{github.workspace}}/NielsSchmidt/NielsSchmidt/Server
      APP_NAME: NielsSchmidt.Server
      VERSION_DOTNET: '6.0'
      RUNTIME_DOTNET: 'linux-x64'
      PACKAGE_NAME: artifact.zip

    runs-on: ubuntu-latest
    steps:
      # #########################################
      # Setup
      # #########################################
      - uses: actions/checkout@v2

      - name: Get TAG version
        run: |
          echo "TAG_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          echo "Version '${GITHUB_REF/refs\/tags\//}'"
        shell: bash

      # #########################################
      # Build DotNet
      # #########################################
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{env.VERSION_DOTNET}}.x

      - name: Publish
        run: dotnet publish "${{env.PATH_BASE_APP}}/${{env.APP_NAME}}.csproj" -p:Version=${{env.TAG_VERSION}} -c Release --runtime ${{env.RUNTIME_DOTNET}} --self-contained </dev/null

      # #########################################
      # Cleanup
      # #########################################
      - name: Cleanup
        run: |
          rm -f ${{env.APP_NAME}}/bin/Release/net${{env.VERSION_DOTNET}}/${{env.RUNTIME_DOTNET}}/publish/appsettings.Development.json
        working-directory: ${{env.PATH_BASE_APP}}

      # #########################################
      # Package
      # #########################################
      - name: Create package
        run: |
          zip -qr ${{env.PACKAGE_NAME}} ./
          mv ./${{env.PACKAGE_NAME}} ${{env.PATH_BASE}}/${{env.PACKAGE_NAME}}
        working-directory: ${{env.PATH_BASE_APP}}/bin/Release/net${{env.VERSION_DOTNET}}/${{env.RUNTIME_DOTNET}}/publish

      # #########################################
      # CoreDeploy
      # #########################################
      - name: Core Deploy
        uses: itniels/CoreDeploy.Action@main
        with:
          appid: 9
          version: ${{env.TAG_VERSION}}
          artifact: ${{env.PATH_BASE}}/${{env.PACKAGE_NAME}}
          message: ${{github.event.head_commit.message}}
          url: ${{secrets.COREDEPLOY_URL}}
          key: ${{secrets.COREDEPLOY_INGRESSKEY}}