name: Docker Image CI

on:
  push:
    tags:
       - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Get TAG version
      run: |
        echo "TAG_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
        echo "Version '${GITHUB_REF/refs\/tags\//}'"
      shell: bash

    - name: Login to registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.REGISTRY_ITNIELS_URL }}
        username: ${{ secrets.REGISTRY_ITNIELS_USERNAME }}
        password: ${{ secrets.REGISTRY_ITNIELS_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ secrets.REGISTRY_ITNIELS_URL }/nielsschmidt.dev:latest
          ${{ secrets.REGISTRY_ITNIELS_URL }}/nielsschmidt.dev:${{ env.TAG_VERSION }}